/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module counter(clk, nrst, clear, enable, max_count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  input clear;
  wire clear;
  input clk;
  wire clk;
  wire [7:0] count_q;
  input enable;
  wire enable;
  output max_count;
  wire max_count;
  input nrst;
  wire nrst;
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(clear),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor4_1 _26_ (
    .A(count_q[5]),
    .B(count_q[4]),
    .C(count_q[7]),
    .D(count_q[6]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand3_1 _27_ (
    .A(count_q[1]),
    .B(count_q[3]),
    .C(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3_1 _28_ (
    .A(count_q[0]),
    .B(count_q[2]),
    .C(_10_),
    .Y(max_count)
  );
  sky130_fd_sc_hd__o31ai_1 _29_ (
    .A1(count_q[0]),
    .A2(count_q[2]),
    .A3(_10_),
    .B1(_08_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(count_q[0]),
    .B(enable),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(_11_),
    .B(_12_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _32_ (
    .A1(count_q[0]),
    .A2(enable),
    .B1(count_q[1]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and3_1 _33_ (
    .A(count_q[1]),
    .B(count_q[0]),
    .C(enable),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _34_ (
    .A(_11_),
    .B(_13_),
    .C(_14_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(count_q[2]),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(_11_),
    .B(_15_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__and3_1 _37_ (
    .A(count_q[2]),
    .B(count_q[3]),
    .C(_14_),
    .X(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(count_q[2]),
    .A2(_14_),
    .B1(count_q[3]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor3_1 _39_ (
    .A(_11_),
    .B(_16_),
    .C(_17_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(count_q[4]),
    .B(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and3_1 _41_ (
    .A(count_q[2]),
    .B(count_q[3]),
    .C(count_q[4]),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2_0 _42_ (
    .A(_14_),
    .B(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nor3_1 _43_ (
    .A(_11_),
    .B(_18_),
    .C(_20_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(count_q[5]),
    .B(_20_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(_11_),
    .B(_21_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand4_1 _46_ (
    .A(count_q[5]),
    .B(count_q[6]),
    .C(_14_),
    .D(_19_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(count_q[5]),
    .A2(_20_),
    .B1(count_q[6]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nor3b_1 _48_ (
    .A(_23_),
    .B(_11_),
    .C_N(_22_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _49_ (
    .A(count_q[7]),
    .B(_22_),
    .X(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_11_),
    .B(_24_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_00_),
    .Q(count_q[0]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_q[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_q[2]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _54_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_q[3]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _55_ (
    .CLK(clk),
    .D(_04_),
    .Q(count_q[4]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _56_ (
    .CLK(clk),
    .D(_05_),
    .Q(count_q[5]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _57_ (
    .CLK(clk),
    .D(_06_),
    .Q(count_q[6]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _58_ (
    .CLK(clk),
    .D(_07_),
    .Q(count_q[7]),
    .RESET_B(nrst)
  );
endmodule

module fsm(clk, nrst, button, count_max, red, yellow, green, count_clr, count_en);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input button;
  wire button;
  input clk;
  wire clk;
  output count_clr;
  wire count_clr;
  output count_en;
  wire count_en;
  input count_max;
  wire count_max;
  output green;
  wire green;
  input nrst;
  wire nrst;
  output red;
  wire red;
  wire [2:0] state_q;
  output yellow;
  wire yellow;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(state_q[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(state_q[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _10_ (
    .A(state_q[2]),
    .SLEEP(state_q[0]),
    .X(count_en)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(state_q[1]),
    .B(button),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _12_ (
    .A1(_03_),
    .A2(count_max),
    .B1(_05_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _13_ (
    .A(state_q[0]),
    .B(count_max),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _14_ (
    .A1(_04_),
    .A2(button),
    .B1(_06_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(state_q[0]),
    .B(count_max),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _16_ (
    .A1(_03_),
    .A2(count_max),
    .B1(_07_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__dfstp_2 _17_ (
    .CLK(clk),
    .D(_00_),
    .Q(state_q[0]),
    .SET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(_01_),
    .Q(state_q[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(_02_),
    .Q(state_q[2]),
    .RESET_B(nrst)
  );
  assign count_clr = state_q[1];
  assign green = state_q[1];
  assign red = state_q[0];
  assign yellow = state_q[2];
endmodule

module top(clk, nrst, button, red, yellow, green);
  input button;
  wire button;
  input clk;
  wire clk;
  wire count_clr;
  wire count_en;
  wire count_max;
  output green;
  wire green;
  input nrst;
  wire nrst;
  output red;
  wire red;
  output yellow;
  wire yellow;
  counter src1 (
    .clear(count_clr),
    .clk(clk),
    .enable(count_en),
    .max_count(count_max),
    .nrst(nrst)
  );
  fsm src2 (
    .button(button),
    .clk(clk),
    .count_clr(count_clr),
    .count_en(count_en),
    .count_max(count_max),
    .green(green),
    .nrst(nrst),
    .red(red),
    .yellow(yellow)
  );
endmodule
