/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module flex_counter(clk, nrst, count_enable, clear, rollover_val, count_out, rollover_flag);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  input clear;
  wire clear;
  input clk;
  wire clk;
  input count_enable;
  wire count_enable;
  output [3:0] count_out;
  wire [3:0] count_out;
  wire [3:0] next_count;
  wire next_flag;
  input nrst;
  wire nrst;
  output rollover_flag;
  wire rollover_flag;
  input [3:0] rollover_val;
  wire [3:0] rollover_val;
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(rollover_val[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(count_out[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _45_ (
    .A(rollover_val[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _46_ (
    .A(count_enable),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _47_ (
    .A(rollover_val[3]),
    .B(count_out[3]),
    .X(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _48_ (
    .A(count_out[2]),
    .SLEEP(rollover_val[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _49_ (
    .A(rollover_val[2]),
    .B(count_out[2]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _51_ (
    .A(count_out[1]),
    .SLEEP(rollover_val[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor3b_1 _52_ (
    .A(_04_),
    .B(_06_),
    .C_N(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__maj3_1 _53_ (
    .A(_00_),
    .B(count_out[3]),
    .C(_05_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _54_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _55_ (
    .A(rollover_val[1]),
    .SLEEP(count_out[1]),
    .X(_12_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _56_ (
    .A(rollover_val[0]),
    .SLEEP(count_out[0]),
    .X(_13_)
  );
  sky130_fd_sc_hd__nor3_1 _57_ (
    .A(_08_),
    .B(_12_),
    .C(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(_07_),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21ba_1 _59_ (
    .A1(_09_),
    .A2(_10_),
    .B1_N(count_out[0]),
    .X(_16_)
  );
  sky130_fd_sc_hd__nor4_1 _60_ (
    .A(rollover_val[3]),
    .B(rollover_val[2]),
    .C(rollover_val[1]),
    .D(rollover_val[0]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__or4_1 _61_ (
    .A(rollover_val[3]),
    .B(rollover_val[2]),
    .C(rollover_val[1]),
    .D(rollover_val[0]),
    .X(_18_)
  );
  sky130_fd_sc_hd__a311o_1 _62_ (
    .A1(count_out[0]),
    .A2(_11_),
    .A3(_15_),
    .B1(_16_),
    .C1(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nor2_1 _63_ (
    .A(count_out[0]),
    .B(count_enable),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a211oi_1 _64_ (
    .A1(count_enable),
    .A2(_19_),
    .B1(_20_),
    .C1(clear),
    .Y(next_count[0])
  );
  sky130_fd_sc_hd__a31oi_1 _65_ (
    .A1(count_out[0]),
    .A2(_11_),
    .A3(_15_),
    .B1(count_out[1]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__and4_1 _66_ (
    .A(count_out[0]),
    .B(count_out[1]),
    .C(_11_),
    .D(_15_),
    .X(_22_)
  );
  sky130_fd_sc_hd__nand2_1 _67_ (
    .A(count_out[0]),
    .B(_02_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nand3_1 _68_ (
    .A(_07_),
    .B(_14_),
    .C(_23_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand2_1 _69_ (
    .A(_18_),
    .B(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o31a_1 _70_ (
    .A1(_21_),
    .A2(_22_),
    .A3(_25_),
    .B1(count_enable),
    .X(_26_)
  );
  sky130_fd_sc_hd__nor2_1 _71_ (
    .A(count_out[1]),
    .B(count_enable),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor3_1 _72_ (
    .A(clear),
    .B(_26_),
    .C(_27_),
    .Y(next_count[1])
  );
  sky130_fd_sc_hd__a31oi_1 _73_ (
    .A1(_07_),
    .A2(_14_),
    .A3(_23_),
    .B1(_01_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a41oi_1 _74_ (
    .A1(count_out[0]),
    .A2(count_out[1]),
    .A3(_11_),
    .A4(_15_),
    .B1(_28_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a211oi_1 _75_ (
    .A1(count_out[2]),
    .A2(_22_),
    .B1(_29_),
    .C1(_17_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a21oi_1 _76_ (
    .A1(_01_),
    .A2(_03_),
    .B1(clear),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o21a_1 _77_ (
    .A1(_03_),
    .A2(_30_),
    .B1(_31_),
    .X(next_count[2])
  );
  sky130_fd_sc_hd__a22o_1 _78_ (
    .A1(count_out[2]),
    .A2(_22_),
    .B1(_24_),
    .B2(count_out[3]),
    .X(_32_)
  );
  sky130_fd_sc_hd__a21oi_1 _79_ (
    .A1(_18_),
    .A2(_32_),
    .B1(_03_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor2_1 _80_ (
    .A(count_out[3]),
    .B(count_enable),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor3_1 _81_ (
    .A(clear),
    .B(_33_),
    .C(_34_),
    .Y(next_count[3])
  );
  sky130_fd_sc_hd__nor4_1 _82_ (
    .A(rollover_val[3]),
    .B(clear),
    .C(_33_),
    .D(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o31a_1 _83_ (
    .A1(clear),
    .A2(_33_),
    .A3(_34_),
    .B1(rollover_val[3]),
    .X(_36_)
  );
  sky130_fd_sc_hd__xnor2_1 _84_ (
    .A(rollover_val[2]),
    .B(next_count[2]),
    .Y(_37_)
  );
  sky130_fd_sc_hd__o31ai_1 _85_ (
    .A1(clear),
    .A2(_26_),
    .A3(_27_),
    .B1(rollover_val[1]),
    .Y(_38_)
  );
  sky130_fd_sc_hd__or4_1 _86_ (
    .A(clear),
    .B(rollover_val[1]),
    .C(_26_),
    .D(_27_),
    .X(_39_)
  );
  sky130_fd_sc_hd__a2111o_1 _87_ (
    .A1(count_enable),
    .A2(_19_),
    .B1(_20_),
    .C1(rollover_val[0]),
    .D1(clear),
    .X(_40_)
  );
  sky130_fd_sc_hd__o211a_1 _88_ (
    .A1(_02_),
    .A2(next_count[0]),
    .B1(_40_),
    .C1(_18_),
    .X(_41_)
  );
  sky130_fd_sc_hd__nand3_1 _89_ (
    .A(_38_),
    .B(_39_),
    .C(_41_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__nor4b_1 _90_ (
    .A(_35_),
    .B(_42_),
    .C(_36_),
    .D_N(_37_),
    .Y(next_flag)
  );
  sky130_fd_sc_hd__dfrtp_1 _91_ (
    .CLK(clk),
    .D(next_count[0]),
    .Q(count_out[0]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _92_ (
    .CLK(clk),
    .D(next_count[1]),
    .Q(count_out[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _93_ (
    .CLK(clk),
    .D(next_count[2]),
    .Q(count_out[2]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _94_ (
    .CLK(clk),
    .D(next_count[3]),
    .Q(count_out[3]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _95_ (
    .CLK(clk),
    .D(next_flag),
    .Q(rollover_flag),
    .RESET_B(nrst)
  );
endmodule
